In [3]:
import numpy as np

# Create and print a numpy array with integers from 1 to 10
array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Perform addition, subtraction, multiplication, and division on the array
arrAdd = np.add(array, 1)
print(arrAdd)
arrSub = np.subtract(array, 2)
print(arrSub)
arrMult = np.multiply(array, 5)
print(arrMult)
arrDiv = np.divide(array, 2)
print(arrDiv)

[ 2  3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7  8]
[ 5 10 15 20 25 30 35 40 45 50]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [8]:
# Task 3: 

import time

# Create a Python list with integers from 1 to 1 000 000
oneMillion = [num for num in range(1, int(1e6)+1)]

# Time the execution of addition operation on the list
start_time = time.time()
list = [i + 10 for i in oneMillion]
end_time = time.time()

# Print the execution time
print('Execution time for list (seconds): ', end_time - start_time)

# Create the array
array = np.array(oneMillion)

# Time the execution of addition operation on the array
start_time = time.time()
array = array + 10
end_time = time.time()

# Print the execution time
print('Execution time for array (seconds): ', end_time - start_time)

### Task 2.1: Creating a Simple ndarray

In [13]:
# Import numpy
import numpy as np

# Create an ndarray using np.array
ndarray = np.array([[1, 2, 3], [2, 4, 6]], np.int32)

# Print the array
print(ndarray)

[[1 2 3]
 [2 4 6]]


### Task 2.2: Exploring ndarray Attributes: shape

In [14]:
# Print the shape of the array
print(ndarray.shape)

(2, 3)


### Task 2.3: Exploring ndarray Attributes: size

In [15]:
# Print the size of the array
print(ndarray.size)

6


### Task 2.4: Exploring ndarray Attributes: ndim

In [16]:
# Print the number of dimensions of the array
print(ndarray.ndim)

2


### Task 2.5: Exploring ndarray Attributes: dtype

In [17]:
# Print the data type of the elements in the array
print(ndarray.dtype)

int32


# Step 3: Creating Ndarrays

### Task 3.1: Creating an Empty Ndarray

In [22]:
# Import numpy
import numpy as np

# Create an empty ndarray
emptyArray = np.empty(2)
print(emptyArray)

[ 2.00746908e-230 -1.77417712e+126]


### Task 3.2: Creating a Zeros Ndarray

In [24]:
# Create a zeros ndarray
zeroArray = np.zeros(3)
print(zeroArray)

[0. 0. 0.]


### Task 3.3: Creating a Ones Ndarray

In [25]:
# Create a ones ndarray
onesArray = np.ones(3)
print(onesArray)

[1. 1. 1.]


### Task 3.4: Creating a Full Ndarray

In [ ]:
# Create a full ndarray
